### ISSUE TITLE
ffmpeg.sws_getContext() throw error message: "System.ArgumentException: An item with the same key has already been added."

### ISSUE THREAD

**Issue by meomeo0110** [Ruslan-B/FFmpeg.AutoGen#104] opened 2019-01-15 02:04 UTC
Hi Ruslan-B,

At version 3.4.0, when ffmpeg.sws_getContext() run under multi threading (50 task), the code: ffmpeg.sws_getContext() throw error message: "System.ArgumentException: An item with the same key has already been added."
```
try
{
    SwsContext* pConvertContext = ffmpeg.sws_getContext(width, height, sourcePixFmt,
                                            width, height, AVPixelFormat.AV_PIX_FMT_BGR24, 
                                            ffmpeg.SWS_FAST_BILINEAR, null, null, null);

}
catch (Exception e)
{
    Console.WriteLine(e);
}
```
I fix it by adding a lock when call sws_getContext():
```
lock(locker)
{
 SwsContext* pConvertContext = ffmpeg.sws_getContext()...
}
```
I searched in the internet and saw the sws_getContext() use: av_malloc() and av_freeContext().
However, I cannot to detect which method cause exception.
Could you confirm the ffmpeg.sws_getContext() use 2 methods above and which method cause error message?

**Comment by zgabi** [comment] 2019-01-15 08:52
No, it is not related to the inner function calls of ffmpeg. You get an exception, which means the problem is in the .net code. If seomthing fails in ffmeg you get an error code or the whole application crashes with AccessViolation:)

The problem you mentioned was fixed by be in 2017 dec 22: https://github.com/Ruslan-B/FFmpeg.AutoGen/pull/81/files

Do you have any reason not to upgrade to 3.4.0.6? (Or 4.x?)

If you can't upgrade I suggest you to first call ffmeg.sws_getContest on a single thread, even fith fake parameters, then later you can call it in multiple threads, because first it initializeing the library.

**Comment by meomeo0110** [comment] 2019-01-16 05:02
Hi zgabi,

Thank you for details explanation and useful information.
I upgrade the version and this exception disappeared.

Thank you very much!

**Comment by meomeo0110** [comment] 2019-01-16 05:12
Hi zgabi,

Although the issue is resolved, I still have concern.
How to your code can fix this issue?
Before I call: ffmpeg.sws_getContext(), there are methods such as: ffmpeg.avformat_alloc_context(), 
ffmpeg.avformat_open_input(), ffmpeg.avformat_find_stream_info() is invoked.
As my previous comment, I also can fix it by locking when can: sws_getContext().

Thank you.

**Comment by Ruslan-B** [comment] 2019-01-16 07:06
The name is race concurrency any might fall. Closing issue.

**Closed by Ruslan-B** 2019-01-16 07:06 UTC

**Comment by zgabi** [comment] 2019-01-16 07:30
avformat_open_input and sws_getContext are in 2 different dlls. Each dll should be initialized separately, which is done when you call the first function in that dll.

When you call the first function from a dll, it loads that and adds to a dictionary.

The PR added a double checked locking to the "loader" function, which first check the dictionary if it already contains the the library ot not. If contains, then returns it wihtout locking. Otherwie it needs a lock, in the lock it check again the libraray and loads+adds it.

**Comment by meomeo0110** [comment] 2019-01-16 08:16
Hi zgabi,

Thank you very much for explanation!
It seem relate to 'partial' class.
