### ISSUE TITLE
Some of the struct not match the C struct (like AVDictionary)

### ISSUE THREAD

**Issue by ZhouJie-BBM** [Ruslan-B/FFmpeg.AutoGen#142] opened 2020-09-09 03:13 UTC
- [x] bug report

* current behavior:
`AVDictionary` in `FFmpeg.AutoGen 4.3.0.1`:

* a minimal demo of the problem, expected behavior:
Console.WriteLine(sizeof(AVDictionary)); // 1, should be 16 in x64

I believe the incomplete struct caused this issue, and AVDictionary struct is defined in dict.c instead of dict.h

* **What is the motivation / use case for changing the behavior?**
Just for fun :)

* Environment info
FFmpeg: 4.3.1 x64 GPL from https://ffmpeg.zeranoe.com/builds/
FFmpeg.AutoGen: 4.3.0.1 from NuGet

**Comment by Ruslan-B** [comment] 2020-09-09 05:13
Duplicate of #141

**Closed by Ruslan-B** 2020-09-09 05:13 UTC

**Comment by sdcb** [comment] 2020-09-09 05:35
Hey @Ruslan-B , I don't think it's a duplicate, `AVDictionary` is incorrect by class in-complete, `AVOption` is incorrect by `union`.

**Comment by Ruslan-B** [comment] 2020-09-20 11:49
Yes, you right it is not a duplicate but if it is defined in ```dict.c ``` than it is not a part of public API. Hence, size will be 1 supposed to be used as pointer and supposed to be created only in unmanaged FFmpeg.
There are quite some of them in ```FFmpeg.structs.incomplete.g.cs```.
