### ISSUE TITLE
Strong name validation failed

### ISSUE THREAD

**Issue by ispysoftware** [Ruslan-B/FFmpeg.AutoGen#296] opened 2024-03-16 23:12 UTC
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ x] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Kind of both

* **What is the current behavior?**
Some deployments of our app is crashing on startup. Probably something to do with an environment policy setting. It looks like the FFmpeg.AutoGen.dll file is badly signed - it needs to either be not signed or properly signed. I tried with 6.1.0.0 as well and had the same issue.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

run 
sn -v FFmpeg.AutoGen.dll

against the nuget dll.

ffmpeg.autogen\6.1.0\lib\netstandard2.0>sn -v FFmpeg.AutoGen.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failed to verify assembly -- Strong name validation failed.

* **What is the expected behavior?**
Either has no strong name or a valid one

* **What is the motivation / use case for changing the behavior?**
Getting errors from deployed applications 

Error:Unhandled Exception: System.TypeInitializationException: The type initializer for 'CoreLogic.Statics' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'FFmpeg.AutoGen, Version=[6.0.0.2](https://6.0.0.2/),

Culture=neutral, PublicKeyToken=9b7632533a381715' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed.

(Exception from HRESULT: 0x8013141A)
* **Please tell us about your environment:**

windows 64

- version: 
all current
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by c72578** [comment] 2024-03-17 05:19
Duplicate of #279

**Comment by ispysoftware** [comment] 2024-03-17 08:48
It's not really a duplicate as strong naming needs to be either working or removed. As it is it's breaking applications.

**Comment by ispysoftware** [comment] 2024-03-26 00:51
We're getting reports of this happening several times a day now - any ETA on a fix for it? I think all that needs to happen is remove the sign step on the build.

**Comment by Ruslan-B** [comment] 2024-03-26 06:44
If I drop it will it fix the problem?

**Comment by ispysoftware** [comment] 2024-03-26 06:59
I think it'll fix my problem - i built from source and removed the code sign and it passes validation

**Comment by Ruslan-B** [comment] 2024-03-26 07:40
Strange it started to occur in first place.

**Comment by Ruslan-B** [comment] 2024-03-27 18:07
@ispysoftware can we close it? I think others can use 3rd party nuget package to add strong name if needed.

**Closed** 2024-03-27 22:04 UTC
